[package]
name = "api"
version = "0.2.0-alpha.64"
edition = "2021"

[[bin]]
name = "api"
path = "src/main.rs"

[[bin]]
name = "generate-gql-schema"
path = "src/bin/generate_gql_schema.rs"

[[bin]]
name = "create-query-engine-role"
path = "src/bin/create_query_engine_role.rs"

[dependencies]
axum = { workspace = true }
bb8 = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
hyper = { workspace = true }
juniper = { workspace = true }
juniper_axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tonic-types = { workspace = true }
prost-types = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ring = { workspace = true }
base64 = { workspace = true }
tower-http = { workspace = true }
argon2 = { workspace = true }
tower = { workspace = true }
jsonwebtoken = { workspace = true }
ipnet = { workspace = true }
heck = { workspace = true }
pin-project-lite = { workspace = true }
diesel_migrations = { version = "2.2.0", features = ["postgres"] }
redis = { version = "0.28.2", features = ["aio", "r2d2", "tokio-comp"] }
r2d2 = "0.8.10"
tokio-stream = "0.1.17"

[dependencies.ptolemy]
path = "../ptolemy"
